"""initial schema

Revision ID: 0674f4a4a074
Revises:
Create Date: 2026-08-20 01:29:59.655070+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0674f4a4a074"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_url", sa.String(length=512), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("sitemap_total", sa.Integer(), nullable=False),
        sa.Column("sitemap_html", sa.Integer(), nullable=False),
        sa.Column("indexed_estimate", sa.Integer(), nullable=True),
        sa.Column("size_tier", sa.String(length=16), nullable=False),
        sa.Column("size_warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan_source", sa.String(length=16), nullable=False),
        sa.Column("site_name", sa.String(length=255), nullable=False),
        sa.Column("site_summary", sa.Text(), nullable=False),
        sa.Column("pattern", sa.String(length=32), nullable=False),
        sa.Column("llmstxt", sa.Text(), nullable=False),
        sa.Column("llms_full", sa.Text(), nullable=False),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_domain"), "runs", ["domain"], unique=False)
    op.create_index("ix_runs_domain_created", "runs", ["domain", "created_at"], unique=False)
    op.create_table(
        "site_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("indexed_estimate", sa.Integer(), nullable=True),
        sa.Column("indexed_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("h1", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("text_ratio", sa.Float(), nullable=False),
        sa.Column("crawl_depth", sa.Integer(), nullable=False),
        sa.Column("folder_depth", sa.Integer(), nullable=False),
        sa.Column("inlinks", sa.Integer(), nullable=False),
        sa.Column("unique_inlinks", sa.Integer(), nullable=False),
        sa.Column("outlinks", sa.Integer(), nullable=False),
        sa.Column("external_outlinks", sa.Integer(), nullable=False),
        sa.Column("link_score", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("canonical", sa.String(length=2048), nullable=False),
        sa.Column("closest_similarity", sa.Float(), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("fetch_tier", sa.String(length=16), nullable=False),
        sa.Column("response_time", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("section_name", sa.String(length=255), nullable=False),
        sa.Column("is_optional", sa.Boolean(), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "url", name="uq_pages_run_url"),
    )
    op.create_index(op.f("ix_pages_run_id"), "pages", ["run_id"], unique=False)
    op.create_index("ix_pages_run_section", "pages", ["run_id", "section_name"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("done", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_run_events_run_at", "run_events", ["run_id", "at"], unique=False)
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    op.create_table(
        "sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "name", name="uq_sections_run_name"),
    )
    op.create_index(op.f("ix_sections_run_id"), "sections", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sections_run_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_index("ix_run_events_run_at", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_pages_run_section", table_name="pages")
    op.drop_index(op.f("ix_pages_run_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_table("site_configs")
    op.drop_index("ix_runs_domain_created", table_name="runs")
    op.drop_index(op.f("ix_runs_domain"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
