"""add artifact_edits

Revision ID: 3e8cf647e6fb
Revises: 7a1a545f239f
Create Date: 2026-08-24 01:25:01.401423+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3e8cf647e6fb"
down_revision: str | None = "7a1a545f239f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_edits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("component_key", sa.String(length=64), nullable=False),
        sa.Column(
            "operations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "facts", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "messages", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("edited_by", sa.String(length=320), nullable=False),
        sa.Column(
            "edited_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain", "component_key", name="uq_artifact_edits_domain_component"),
    )
    op.create_index(op.f("ix_artifact_edits_domain"), "artifact_edits", ["domain"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifact_edits_domain"), table_name="artifact_edits")
    op.drop_table("artifact_edits")
    # ### end Alembic commands ###
