"""record interactive llm spend

Revision ID: 50c248cd3b5d
Revises: 3e8cf647e6fb
Create Date: 2026-08-24 06:21:36.104583+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '50c248cd3b5d'
down_revision: str | None = '3e8cf647e6fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_spend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('fallbacks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('spent_by', sa.String(length=320), nullable=False),
    sa.Column('spent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_spend_domain'), 'llm_spend', ['domain'], unique=False)
    op.create_index(op.f('ix_llm_spend_spent_at'), 'llm_spend', ['spent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_spend_spent_at'), table_name='llm_spend')
    op.drop_index(op.f('ix_llm_spend_domain'), table_name='llm_spend')
    op.drop_table('llm_spend')
    # ### end Alembic commands ###
