"""chat editing

Revision ID: 9357e0271021
Revises: dcd5c266f8c3
Create Date: 2026-08-20 05:26:38.144857+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9357e0271021"
down_revision: str | None = "dcd5c266f8c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("operations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rejected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author", sa.String(length=320), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chat_messages_run_at", "chat_messages", ["run_id", "at"], unique=False)
    op.create_index(op.f("ix_chat_messages_run_id"), "chat_messages", ["run_id"], unique=False)
    op.create_table(
        "document_revisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("llmstxt", sa.Text(), nullable=False),
        sa.Column("llms_full", sa.Text(), nullable=False),
        sa.Column("pages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("site_name", sa.String(length=255), nullable=False),
        sa.Column("site_summary", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=320), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_revisions_run_at", "document_revisions", ["run_id", "at"], unique=False
    )
    op.create_index(
        op.f("ix_document_revisions_run_id"), "document_revisions", ["run_id"], unique=False
    )
    # server_default is required, not cosmetic: adding a NOT NULL column to a
    # table that already has rows fails without one.
    op.add_column(
        "runs",
        sa.Column("notes", sa.Text(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "notes")
    op.drop_index(op.f("ix_document_revisions_run_id"), table_name="document_revisions")
    op.drop_index("ix_document_revisions_run_at", table_name="document_revisions")
    op.drop_table("document_revisions")
    op.drop_index(op.f("ix_chat_messages_run_id"), table_name="chat_messages")
    op.drop_index("ix_chat_messages_run_at", table_name="chat_messages")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
