"""site metrics

Revision ID: d359a525827a
Revises: b3e91f70c4aa
Create Date: 2026-08-20 08:37:58.188846+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d359a525827a"
down_revision: str | None = "b3e91f70c4aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("ctr", sa.Float(), nullable=True),
        sa.Column("position", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=True),
        sa.Column("window_end", sa.Date(), nullable=True),
        sa.Column("uploaded_by", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain", "url", "source", name="uq_site_metrics_domain_url_source"),
    )
    op.create_index(op.f("ix_site_metrics_domain"), "site_metrics", ["domain"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverses the schema, not the data.

    Dropping the site_metrics table discards every answer stored in it. Tested against
    populated rows: the migration runs cleanly and the content is gone. Treat
    this as a schema rollback only -- take a dump first if the rows matter.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_metrics_domain"), table_name="site_metrics")
    op.drop_table("site_metrics")
    # ### end Alembic commands ###
