"""observed site shape

Revision ID: db6b5dbeeea3
Revises: d359a525827a
Create Date: 2026-08-20 08:48:40.659943+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'db6b5dbeeea3'
down_revision: str | None = 'd359a525827a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_configs', sa.Column('observed_shape', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverses the schema, not the data.

    Dropping site_configs.observed_shape discards every answer stored in it. Tested against
    populated rows: the migration runs cleanly and the content is gone. Treat
    this as a schema rollback only -- take a dump first if the rows matter.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_configs', 'observed_shape')
    # ### end Alembic commands ###
