"""component marks

Revision ID: dcc63583bd97
Revises: db6b5dbeeea3
Create Date: 2026-08-20 12:29:26.207509+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dcc63583bd97"
down_revision: str | None = "db6b5dbeeea3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "component_marks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("component_key", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("noted_by", sa.String(length=320), nullable=False),
        sa.Column(
            "noted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain", "component_key", name="uq_component_marks_domain_key"),
    )
    op.create_index(op.f("ix_component_marks_domain"), "component_marks", ["domain"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_component_marks_domain"), table_name="component_marks")
    op.drop_table("component_marks")
    # ### end Alembic commands ###
